// examples/Wails.Net.Demo.Vue/frontend/src/components/SystemPanel.tsx
import { defineComponent, ref } from 'vue'

interface ServerInfoEntry {
  key: string
  value: string
}

export default defineComponent({
  name: 'SystemPanel',
  setup() {
    const serverInfo = ref<ServerInfoEntry[]>([])
    const clipboardInput = ref('Hello, Wails.Net!')
    const clipboardResult = ref('')
    const notificationInput = ref('这是一条来自 Vue JSX Vapor 前端的通知')
    const windowMessage = ref('')

    const onGetServerInfo = async () => {
      try {
        const info = await window.wails.call('GreetingService.GetServerInfo', [])
        if (info && typeof info === 'object') {
          serverInfo.value = Object.entries(info as Record<string, string>).map(
            ([key, value]) => ({ key, value: String(value) }),
          )
        } else {
          serverInfo.value = [{ key: '结果', value: String(info) }]
        }
      } catch (e) {
        console.error('获取服务器信息失败:', e)
        serverInfo.value = [{ key: '错误', value: String(e) }]
      }
    }

    const onCopy = async () => {
      const text = clipboardInput.value
      if (!text) return
      try {
        await window.wails.call('clipboard.setText', [text])
        clipboardResult.value = '已复制到剪贴板'
      } catch (e) {
        console.error('复制失败:', e)
        clipboardResult.value = '复制失败'
      }
    }

    const onPaste = async () => {
      try {
        const text = await window.wails.call('clipboard.getText', [])
        clipboardResult.value = `剪贴板内容: ${text}`
      } catch (e) {
        console.error('粘贴失败:', e)
        clipboardResult.value = '粘贴失败'
      }
    }

    const onNotify = async () => {
      const text = notificationInput.value
      if (!text) return
      try {
        await window.wails.call('notification.send', [
          { title: 'Wails.Net Vue Demo', body: text },
        ])
      } catch (e) {
        console.error('发送通知失败:', e)
      }
    }

    const onSetTitle = async () => {
      try {
        await window.wails.window.setTitle('新标题 - 来自 Vue JSX Vapor')
        windowMessage.value = '窗口标题已更新'
      } catch (e) {
        console.error('设置窗口标题失败:', e)
        windowMessage.value = '设置窗口标题失败'
      }
    }

    const onMinimize = async () => {
      try {
        await window.wails.window.minimize()
        windowMessage.value = '窗口已最小化'
      } catch (e) {
        console.error('最小化窗口失败:', e)
        windowMessage.value = '最小化窗口失败'
      }
    }

    const onMaximize = async () => {
      try {
        await window.wails.window.maximize()
        windowMessage.value = '窗口已最大化'
      } catch (e) {
        console.error('最大化窗口失败:', e)
        windowMessage.value = '最大化窗口失败'
      }
    }

    const onCentre = async () => {
      try {
        await window.wails.window.centre()
        windowMessage.value = '窗口已居中'
      } catch (e) {
        console.error('居中窗口失败:', e)
        windowMessage.value = '居中窗口失败'
      }
    }

    return () => (
      <div class="panel">
        <h2>系统信息</h2>
        <p class="description">演示服务器信息、剪贴板、通知与窗口操作的绑定调用</p>

        <h3>服务器信息</h3>
        <div class="form-group">
          <button class="btn" onClick={onGetServerInfo}>
            获取服务器信息
          </button>
        </div>
        {serverInfo.value.length > 0 && (
          <div class="result">
            {serverInfo.value.map((entry) => (
              <div class="info-row" key={entry.key}>
                <strong>{entry.key}:</strong> {entry.value}
              </div>
            ))}
          </div>
        )}

        <h3>剪贴板</h3>
        <div class="form-group">
          <input
            type="text"
            value={clipboardInput.value}
            onInput={(e) =>
              (clipboardInput.value = (e.target as HTMLInputElement).value)
            }
          />
          <button class="btn" onClick={onCopy}>
            复制
          </button>
          <button class="btn" onClick={onPaste}>
            粘贴
          </button>
        </div>
        {clipboardResult.value && <div class="result">{clipboardResult.value}</div>}

        <h3>系统通知</h3>
        <div class="form-group">
          <input
            type="text"
            value={notificationInput.value}
            onInput={(e) =>
              (notificationInput.value = (e.target as HTMLInputElement).value)
            }
          />
          <button class="btn" onClick={onNotify}>
            发送通知
          </button>
        </div>

        <h3>窗口操作</h3>
        <div class="form-group">
          <button class="btn" onClick={onSetTitle}>
            设置标题
          </button>
          <button class="btn" onClick={onMinimize}>
            最小化
          </button>
          <button class="btn" onClick={onMaximize}>
            最大化
          </button>
          <button class="btn" onClick={onCentre}>
            居中
          </button>
        </div>
        {windowMessage.value && <div class="result">{windowMessage.value}</div>}
      </div>
    )
  },
})

// examples/Wails.Net.Demo.React/frontend/src/components/SystemPanel.tsx
import { useEffect, useState } from 'react'

interface ServerInfo {
  [key: string]: string | number | boolean
}

export default function SystemPanel() {
  const [info, setInfo] = useState<ServerInfo | null>(null)
  const [error, setError] = useState('')
  const [clipText, setClipText] = useState('')
  const [notifyResult, setNotifyResult] = useState('')
  const [windowResult, setWindowResult] = useState('')

  const loadServerInfo = async () => {
    try {
      const result = await window.wails.call('GreetingService.GetServerInfo', [])
      setInfo(result as ServerInfo)
      setError('')
    } catch (e) {
      console.error(e)
      setError('获取服务器信息失败：' + String(e))
    }
  }

  useEffect(() => {
    loadServerInfo()
  }, [])

  const onCopy = async () => {
    try {
      const text = info ? JSON.stringify(info, null, 2) : ''
      await window.wails.call('clipboard.setText', [text])
      setClipText(text)
      setError('')
    } catch (e) {
      console.error(e)
      setError('复制到剪贴板失败：' + String(e))
    }
  }

  const onPaste = async () => {
    try {
      const text = await window.wails.call('clipboard.getText', [])
      setClipText(String(text))
      setError('')
    } catch (e) {
      console.error(e)
      setError('从剪贴板粘贴失败：' + String(e))
    }
  }

  const onNotify = async () => {
    try {
      const body = info ? `服务运行中，共 ${Object.keys(info).length} 项信息` : '服务器信息未加载'
      await window.wails.call('notification.send', [
        { title: 'Wails.Net React Demo', body },
      ])
      setNotifyResult('通知已发送')
      setError('')
    } catch (e) {
      console.error(e)
      setError('发送通知失败：' + String(e))
    }
  }

  const onSetTitle = async () => {
    try {
      await window.wails.window.setTitle('Wails.Net React Demo - 新标题')
      setWindowResult('窗口标题已更新')
      setError('')
    } catch (e) {
      console.error(e)
      setError('设置标题失败：' + String(e))
    }
  }

  const onMinimize = async () => {
    try {
      await window.wails.window.minimize()
      setWindowResult('窗口已最小化')
      setError('')
    } catch (e) {
      console.error(e)
      setError('最小化失败：' + String(e))
    }
  }

  const onMaximize = async () => {
    try {
      await window.wails.window.maximize()
      setWindowResult('窗口已最大化')
      setError('')
    } catch (e) {
      console.error(e)
      setError('最大化失败：' + String(e))
    }
  }

  const onCentre = async () => {
    try {
      await window.wails.window.centre()
      setWindowResult('窗口已居中')
      setError('')
    } catch (e) {
      console.error(e)
      setError('居中失败：' + String(e))
    }
  }

  const onAlwaysOnTop = async () => {
    try {
      await window.wails.window.setAlwaysOnTop(true)
      setWindowResult('窗口已置顶')
      setError('')
    } catch (e) {
      console.error(e)
      setError('置顶失败：' + String(e))
    }
  }

  const onOpenDevTools = async () => {
    try {
      await window.wails.window.openDevTools()
      setWindowResult('开发者工具已打开')
      setError('')
    } catch (e) {
      console.error(e)
      setError('打开开发者工具失败：' + String(e))
    }
  }

  return (
    <div className="panel">
      <h2>系统信息</h2>
      <p className="description">演示服务器信息、剪贴板、通知和窗口操作</p>

      <h3>服务器信息</h3>
      <div className="form-group">
        <button className="btn btn-small" onClick={loadServerInfo}>刷新信息</button>
        <button className="btn btn-small" onClick={onCopy}>复制到剪贴板</button>
        <button className="btn btn-small" onClick={onPaste}>从剪贴板粘贴</button>
      </div>
      {info && (
        <div className="result">
          {Object.entries(info).map(([key, val]) => (
            <div className="info-row" key={key}>
              <strong>{key}</strong>: {String(val)}
            </div>
          ))}
        </div>
      )}

      <h3>剪贴板内容</h3>
      <div className="result">{clipText || '(空)'}</div>

      <h3>通知</h3>
      <div className="form-group">
        <button className="btn" onClick={onNotify}>发送通知</button>
      </div>
      {notifyResult && <div className="result">{notifyResult}</div>}

      <h3>窗口操作</h3>
      <div className="form-group">
        <button className="btn btn-small" onClick={onSetTitle}>设置标题</button>
        <button className="btn btn-small" onClick={onMinimize}>最小化</button>
        <button className="btn btn-small" onClick={onMaximize}>最大化</button>
        <button className="btn btn-small" onClick={onCentre}>居中</button>
        <button className="btn btn-small" onClick={onAlwaysOnTop}>置顶</button>
        <button className="btn btn-small" onClick={onOpenDevTools}>开发者工具</button>
      </div>
      {windowResult && <div className="result">{windowResult}</div>}

      {error && <div className="result">{error}</div>}
    </div>
  )
}
