// examples/Wails.Net.Demo.Vue/frontend/src/App.tsx
import { defineComponent, ref, type Component } from 'vue'
import Greeting from './components/Greeting'
import Todo from './components/Todo'
import Counter from './components/Counter'
import SystemPanel from './components/SystemPanel'

interface TabItem {
  key: string
  label: string
  component: Component
}

export default defineComponent({
  name: 'App',
  setup() {
    const tabs: TabItem[] = [
      { key: 'greeting', label: '问候服务', component: Greeting },
      { key: 'todo', label: '待办事项', component: Todo },
      { key: 'counter', label: '计数器插件', component: Counter },
      { key: 'system', label: '系统信息', component: SystemPanel },
    ]

    const activeTab = ref<string>('greeting')

    const currentComponent = (): Component => {
      const found = tabs.find((t) => t.key === activeTab.value)
      return found ? found.component : Greeting
    }

    return () => (
      <div class="app">
        <div class="header">
          <h1>Wails.Net Vue Demo</h1>
          <p class="subtitle">Vue 3.5 + vue-jsx-vapor + TypeScript + TSX（无 SFC 模板）</p>
        </div>

        <div class="tabs">
          {tabs.map((tab) => (
            <button
              key={tab.key}
              class={'tab' + (activeTab.value === tab.key ? ' active' : '')}
              onClick={() => (activeTab.value = tab.key)}
            >
              {tab.label}
            </button>
          ))}
        </div>

        {(() => {
          const Comp = currentComponent()
          return <Comp />
        })()}
      </div>
    )
  },
})

// examples/Wails.Net.Demo.React/frontend/src/App.tsx
import { useState } from 'react'
import Greeting from './components/Greeting'
import Todo from './components/Todo'
import Counter from './components/Counter'
import SystemPanel from './components/SystemPanel'

type TabKey = 'greeting' | 'todo' | 'counter' | 'system'

interface TabItem {
  key: TabKey
  label: string
}

const tabs: TabItem[] = [
  { key: 'greeting', label: '问候服务' },
  { key: 'todo', label: '待办事项' },
  { key: 'counter', label: '计数器插件' },
  { key: 'system', label: '系统信息' },
]

export default function App() {
  const [activeTab, setActiveTab] = useState<TabKey>('greeting')

  return (
    <div className="app">
      <header className="header">
        <h1>Wails.Net React Demo</h1>
        <p className="subtitle">.NET 10 + React 18 + Vite 6 + TypeScript TSX</p>
      </header>

      <nav className="tabs">
        {tabs.map((tab) => (
          <button
            key={tab.key}
            className={`tab ${activeTab === tab.key ? 'active' : ''}`}
            onClick={() => setActiveTab(tab.key)}
          >
            {tab.label}
          </button>
        ))}
      </nav>

      {activeTab === 'greeting' && <Greeting />}
      {activeTab === 'todo' && <Todo />}
      {activeTab === 'counter' && <Counter />}
      {activeTab === 'system' && <SystemPanel />}
    </div>
  )
}
